services:
  relay:
    build: ./relay
    container_name: p2p-relay
    restart: unless-stopped
    ports:
      - "4003:4003/tcp"
      - "4003:4003/udp"
    environment:
      - RELAY_LISTEN=/ip4/0.0.0.0/tcp/4003
      - RELAY_PRIVATE=false
    volumes:
      - relay-data:/data

  node1:
    build: ./node
    container_name: p2p-node-1
    restart: unless-stopped
    environment:
      - APP_ROOM=${APP_ROOM}
      - RELAY_ADDR=${RELAY_ADDR}
      - LISTEN_TCP=/ip4/0.0.0.0/tcp/4001
      - LISTEN_QUIC=/ip4/0.0.0.0/udp/4001/quic-v1
      - ENABLE_RELAY_CLIENT=${ENABLE_RELAY_CLIENT}
      - ENABLE_HOLEPUNCH=${ENABLE_HOLEPUNCH}
      - ENABLE_UPNP=${ENABLE_UPNP}
      - WEB_ADDR=:3000
      - NODE_NICK=node1
    ports:
      - "4001:4001/tcp"
      - "4001:4001/udp"
      - "3001:3000/tcp"
    # เพิ่ม sysctls เพื่อขยาย UDP/TCP buffer ใน network namespace ของ container
    sysctls:
      net.core.rmem_max: 8388608     # 8 MiB
      net.core.rmem_default: 8388608
      net.core.wmem_max: 8388608
      net.core.wmem_default: 8388608
    # ไม่จำเป็นต้องใช้ NET_ADMIN สำหรับ sysctls ชุดนี้ แต่ถ้าบางระบบต้องการค่อยเปิด
    # cap_add:
    #   - NET_ADMIN
    volumes:
      - node1-data:/data
    depends_on:
      - relay
  node2:
    build: ./node
    container_name: p2p-node-2
    restart: unless-stopped
    environment:
      - APP_ROOM=${APP_ROOM}
      - RELAY_ADDR=${RELAY_ADDR}
      - LISTEN_TCP=/ip4/0.0.0.0/tcp/4001
      - LISTEN_QUIC=/ip4/0.0.0.0/udp/4001/quic-v1
      - ENABLE_RELAY_CLIENT=${ENABLE_RELAY_CLIENT}
      - ENABLE_HOLEPUNCH=${ENABLE_HOLEPUNCH}
      - ENABLE_UPNP=${ENABLE_UPNP}
      - WEB_ADDR=:3000
      - NODE_NICK=node2
    ports:
      - "4002:4001/tcp"
      - "4002:4001/udp"
      - "3002:3000/tcp"
    sysctls:
      net.core.rmem_max: 8388608
      net.core.rmem_default: 8388608
      net.core.wmem_max: 8388608
      net.core.wmem_default: 8388608
    # cap_add:
    #   - NET_ADMIN
    volumes:
      - node2-data:/data
    depends_on:
      - relay

volumes:
  relay-data:
  node1-data:
  node2-data: