version: "3.9"

services:
  relay:
    build: ./relay
    container_name: p2p-relay
    restart: unless-stopped
    # ต้องอยู่บนเครื่องที่เปิดพอร์ตสาธารณะได้ เพื่อความชัวร์
    ports:
      - "4003:4003/tcp"
      - "4003:4003/udp"   # เผื่ออนาคตใช้ QUIC ผ่านรีเลย์
    environment:
      - RELAY_LISTEN=/ip4/0.0.0.0/tcp/4003
      - RELAY_PRIVATE=false
    volumes:
      - relay-data:/data

  node1:
    build: ./node
    container_name: p2p-node-1
    restart: unless-stopped
    environment:
      - APP_ROOM=my-room            # ชื่อห้อง/กลุ่ม (rendezvous string)
      - RELAY_ADDR=/ip4/<YOUR_PUBLIC_IP>/tcp/4003/p2p/<RELAY_PEER_ID>
      - LISTEN_TCP=/ip4/0.0.0.0/tcp/4001
      - LISTEN_QUIC=/ip4/0.0.0.0/udp/4001/quic-v1
      - ENABLE_RELAY_CLIENT=true
      - ENABLE_HOLEPUNCH=true
      - ENABLE_UPNP=true
    ports:
      - "4001:4001/tcp"
      - "4001:4001/udp"
    volumes:
      - node1-data:/data
    depends_on:
      - relay

  node2:
    build: ./node
    container_name: p2p-node-2
    restart: unless-stopped
    environment:
      - APP_ROOM=my-room
      - RELAY_ADDR=/ip4/<YOUR_PUBLIC_IP>/tcp/4003/p2p/<RELAY_PEER_ID>
      - LISTEN_TCP=/ip4/0.0.0.0/tcp/4002
      - LISTEN_QUIC=/ip4/0.0.0.0/udp/4002/quic-v1
      - ENABLE_RELAY_CLIENT=true
      - ENABLE_HOLEPUNCH=true
      - ENABLE_UPNP=true
    ports:
      - "4002:4002/tcp"
      - "4002:4002/udp"
    volumes:
      - node2-data:/data
    depends_on:
      - relay

volumes:
  relay-data:
  node1-data:
  node2-data:
